.DEFAULT_GOAL := all

.PHONY: all
all: ## Show the available make targets.
	@echo "Usage: make <target>"
	@echo ""
	@echo "Targets:"
	@fgrep "##" Makefile | fgrep -v fgrep

.PHONY: clean
clean: ## Clean the temporary files.
	rm -rf .pytest_cache
	rm -rf .coverage
	rm -rf .ruff_cache

.PHONY: format
format:  ## Format the code using Ruff.
	{{ package_manager }} run ruff format .
	{{ package_manager }} run ruff check . --fix

.PHONY: lint
lint:  ## Run all linters (ruff).
	{{ package_manager }} run ruff check .

.PHONY: security-scan
security-scan:  ## Run security scan using Bandit.
	{{ package_manager }} run bandit -r {{ module_name }}

.PHONY: test
test:  ## Run the tests and check coverage.
	{{ package_manager }} run pytest -n auto --cov={{ module_name }} --cov-report term-missing --cov-fail-under=100

.PHONY: install
install:  ## Install the dependencies excluding dev.
	{% if package_manager == "poetry" -%}
	poetry install --only main
	{%- elif package_manager == "pipenv" -%}
	pipenv install
	{%- endif %}

.PHONY: install-dev
install-dev:  ## Install the dependencies including dev.
	{% if package_manager == "poetry" -%}
	poetry install
	{%- elif package_manager == "pipenv" -%}
	pipenv install --dev
	{%- endif %}

{% if enable_copier_updates %}
.PHONY: copier-update
copier-update:  ## Update the project using the initial copier template.
	{{ package_manager }} run copier update --trust
{%- endif %}
